### ISSUE TITLE
Build.fsx fails on build step with error

### ISSUE THREAD

**Issue by quintusm** [fsprojects/ExcelProvider#74]
### Description

If you check out the repo on a windows 10 machine and attempt to build it by running build.cmd the build fails after downloading dotnet sdk 2.1.401 and attempting to unzip it.

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A
Clone the repository to local windows 10 machine with Visual Studio and/or Visual Code installed

2. Step B
Attempt to build by running build.cmd on the command line

### Expected behavior
The system should build successfully

### Actual behavior

The system fails to build.   It attempts to download sdk 2.1.401 and then to unzip it.  Failure message copied below :
Downloading 'https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.401/dotnet-dev-win-x64.2.1.401.zip' to 'C:\Users\aaa\AppData\Local\Temp\dotnet-dev-win-x64.2.1.401.zip'
Running build failed.
Error:
ICSharpCode.SharpZipLib.Zip.ZipException: Cannot find central directory
   at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(String name)
   at Fake.ZipHelper.Unzip(String target, String fileName) in D:\code\fake\src\app\FakeLib\ZipHelper.fs:line 89
   at Fake.DotNetCli.InstallDotNetSDK(String sdkVersion) in D:\code\fake\src\app\FakeLib\DotNetCLIHelper.fs:line 567
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at FSI_0005.Build.clo@143-11.Invoke(BuildParams p)
   at Fake.DotNetCli.Build(FSharpFunc`2 setBuildParams) in D:\code\fake\src\app\FakeLib\DotNetCLIHelper.fs:line 203
   at FSI_0005.Build.clo@139-10.Invoke(Unit _arg6)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target         Duration
------         --------
Clean          00:00:00.0042845
AssemblyInfo   00:00:00.0784046
Build          Failure
Total:         00:00:01.2714281
---------------------------------------------------------------------
Status:        Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) ICSharpCode.SharpZipLib.Zip.ZipException: Cannot find central directory
   at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(String name)
   at Fake.ZipHelper.Unzip(String target, String fileName) in D:\code\fake\src\app\FakeLib\ZipHelper.fs:line 89
   at Fake.DotNetCli.InstallDotNetSDK(String sdkVersion) in D:\code\fake\src\app\FakeLib\DotNetCLIHelper.fs:line 567
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at FSI_0005.Build.clo@143-11.Invoke(BuildParams p)
   at Fake.DotNetCli.Build(FSharpFunc`2 setBuildParams) in D:\code\fake\src\app\FakeLib\DotNetCLIHelper.fs:line 203
   at FSI_0005.Build.clo@139-10.Invoke(Unit _arg6)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
---------------------------------------------------------------------

### Known workarounds

No known workarounds at this time

### Related information 

* Operating system
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by dsyme** [comment]
Hi @quintusm, would you like to become a co-maintainer on this repo?

**Comment by quintusm** [comment]
Hi @dsyme. Yes I would...  I think you actually did already add me before.

I am currently busy in background trying to move build.fsx to Fake 5 but it is taking longer than anticipated.  I think once that is done it will be easier to sort out other issues coming up.

**Comment by dsyme** [comment]
@quintusm You're right, here: https://github.com/fsprojects/ExcelProvider/pull/48 

I've updated the README.md :-)

**Comment by quintusm** [comment]
@dsyme Thanks
